"""PostgreSQL-backed and fixture-safe background job queue."""

from .models import (
    BlueskyCandidateWrite,
    BlueskyDeletion,
    BlueskyDeletionWrite,
    BlueskyJetstreamCompletion,
    BlueskySourceItemWrite,
    CompletionEffect,
    Job,
    JobStatus,
    NostrCandidateWrite,
    NostrDeletionWrite,
    NostrRelayCompletion,
    PublicStudyCompletion,
    TCGdexSetsSyncCompletion,
    TCGdexSetWrite,
    TCGdexSyncOutcome,
    YouTubeDiscoveryCompletion,
    YouTubeSourceItemWrite,
)
from .postgres import (
    CLAIM_SQL,
    NOSTR_CLAIM_SQL,
    NOSTR_FAIL_SQL,
    NOSTR_HEARTBEAT_SQL,
    NOSTR_PAUSE_BUDGET_SQL,
    NostrPostgresJobRepository,
    PostgresJobRepository,
    QueryExecutor,
)
from .repository import (
    InMemoryJobRepository,
    JobNotFoundError,
    JobRepositoryError,
    LeaseLostError,
)

__all__ = [
    "CLAIM_SQL",
    "NOSTR_CLAIM_SQL",
    "NOSTR_FAIL_SQL",
    "NOSTR_HEARTBEAT_SQL",
    "NOSTR_PAUSE_BUDGET_SQL",
    "BlueskyCandidateWrite",
    "BlueskyDeletion",
    "BlueskyDeletionWrite",
    "BlueskyJetstreamCompletion",
    "BlueskySourceItemWrite",
    "CompletionEffect",
    "InMemoryJobRepository",
    "Job",
    "JobNotFoundError",
    "JobRepositoryError",
    "JobStatus",
    "LeaseLostError",
    "NostrCandidateWrite",
    "NostrDeletionWrite",
    "NostrRelayCompletion",
    "NostrPostgresJobRepository",
    "PostgresJobRepository",
    "PublicStudyCompletion",
    "QueryExecutor",
    "TCGdexSetsSyncCompletion",
    "TCGdexSetWrite",
    "TCGdexSyncOutcome",
    "YouTubeDiscoveryCompletion",
    "YouTubeSourceItemWrite",
]
