begin;

-- Generated by Supabase CLI 2.116.0 on MAM as 20260908034244;
-- ordered after the existing future-dated 20261013 migration ledger.
-- Native source labels remain unnormalized. No inferred opening location.
do $migration$
declare
  definition text;
  old_suffix text := $old$      array['バラ100パック開けてみた結果【ポケカ-スターバース編】']::text[]
    );$old$;
  new_suffix text := $new$      array['バラ100パック開けてみた結果【ポケカ-スターバース編】']::text[]
    ),
    (
      28, 'nanjakorya-paradigm-jp-100-v1'::text,
      'public_study_nanjakorya_paradigm_100'::text,
      'nanjakorya_paradigm_trigger_study'::text,
      'Nanjakorya Paradigm Trigger 100-pack study'::text,
      'One 100-pack Paradigm Trigger cohort, four consecutive groups (30/10/30/30). Native reported RR14 RRR7 SR1 HR2; source card labels contain inconsistencies, so these are not normalized hit-rate numerators. Japanese product market only; physical opening place/date unknown. Observation timestamp is publication.'::text,
      'Nanjakorya Paradigm Trigger 100-pack coverage'::text,
      'nanjakorya.com'::text,
      'https://nanjakorya.com/1823'::text,
      'public-study-nanjakorya-paradigm-v1'::text,
      '{
  "study_key": "nanjakorya-paradigm-jp-100-v1",
  "canonical_url": "https://nanjakorya.com/1823",
  "collector_version": "public-study-nanjakorya-paradigm-v1",
  "parser_version": "nanjakorya-paradigm-evidence-v1",
  "country_code": "JP",
  "country_name": "Japan",
  "geography_basis": "product_market",
  "geography_confidence": "tier_b",
  "set_external_id": "s12",
  "set_language": "ja",
  "set_name": "Paradigm Trigger",
  "product_scope": "all",
  "pack_count": 100,
  "observed_at": "2022-10-21T11:10:35Z",
  "denominator_complete": true,
  "set_official_url": "https://www.pokemon-card.com/ex/s12/index.html",
  "robots_url": "https://nanjakorya.com/robots.txt",
  "robots_checked_at": "2026-09-08",
  "terms_checked_at": "2026-09-08",
  "terms_status": "no_independent_terms_page",
  "rights_scope": "minimal_noncreative_facts_no_media_or_body_reuse",
  "rarity_card_counts": {"RR":14,"RRR":7,"SR":1,"HR":2},
  "purchase_group_pack_counts": [30,10,30,30],
  "source_label_inconsistencies": true,
  "opening_country": null,
  "opened_at": null,
  "report_evidence_sha256": "e34a7b2043134f3c8ed6d62b024b64bf3d9c8503a0f3c66564ecbbc36b8b6b6c"
}'::jsonb,
      E'パラダイムトリガー開封結果まとめ'::text,
      array['パラダイムトリガー開封結果まとめ']::text[]
    );$new$;
begin
  select pg_get_functiondef('ingest.reviewed_public_study_contracts()'::regprocedure)
    into definition;
  if position(old_suffix in definition) = 0
    or (select array_agg(ordinal order by ordinal) from ingest.reviewed_public_study_contracts())
       is distinct from array(select generate_series(1, 27)) then
    raise exception 'Expected exact ordinal-27 reviewed-study registry';
  end if;
  execute replace(definition, old_suffix, new_suffix);
end;
$migration$;

alter function ingest.reviewed_public_study_contracts() owner to postgres;
revoke all on function ingest.reviewed_public_study_contracts()
  from public, anon, authenticated, service_role;

insert into ingest.source_policies (
  source_key, display_name, source_kind, domain, base_url, enabled,
  collector_type, access_mode, robots_policy, routes, include_subdomains,
  min_delay_seconds, max_pages_per_run, max_items_per_run, max_concurrency,
  statistics_eligible_default, retention_days, config, version,
  expected_interval_seconds, is_demo
)
select policy_key, display_name, 'public_web', domain, canonical_url, true,
  'scrapling_http', 'public', 'respect', array['scrapling_http']::text[], false,
  30, 2, 1, 1, true, 730, config, policy_version, 86400, false
from ingest.reviewed_public_study_contracts()
where ordinal = 28 and study_key = 'nanjakorya-paradigm-jp-100-v1';

insert into ingest.source_request_gates(source_key)
values ('public_study_nanjakorya_paradigm_100');

do $migration$
declare
  definition text;
  old_tail text := $old$'public_study_nanjakorya_jp_100'$old$;
begin
  select pg_get_functiondef('ingest.reviewed_public_study_gates_ready_v1()'::regprocedure)
    into definition;
  if position('count(*) = 27' in definition) = 0
    or position(old_tail in definition) = 0 then
    raise exception 'Expected ordinal-27 gate readiness function';
  end if;
  execute replace(replace(definition, 'count(*) = 27', 'count(*) = 28'),
    old_tail, old_tail || ', ''public_study_nanjakorya_paradigm_100''');
end;
$migration$;

do $migration$
declare
  function_oid regprocedure;
  definition text;
  old_predicate text := 'contracts.ordinal in (3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27)';
  new_predicate text := 'contracts.ordinal in (3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28)';
begin
  foreach function_oid in array array[
    'ingest.begin_public_study_job_v2(uuid,text,bigint,text)'::regprocedure,
    'ingest.finalize_public_study_coverage_job_v1(uuid,text,bigint,text,jsonb)'::regprocedure,
    'ingest.enqueue_public_study_coverage_job_v1(text,integer,text,timestamptz,integer)'::regprocedure,
    'ingest.enqueue_scheduled_public_study_coverage_job_v1(text,timestamptz,text,integer,integer)'::regprocedure
  ] loop
    definition := pg_get_functiondef(function_oid::oid);
    if position(old_predicate in definition) = 0 then
      raise exception 'Expected ordinal-27 coverage boundary: %', function_oid;
    end if;
    execute replace(definition, old_predicate, new_predicate);
  end loop;
end;
$migration$;

do $migration$
declare
  definition text;
  needle text := $needle$'nanjakorya-star-birth-jp-100-v1'::text$needle$;
begin
  select pg_get_constraintdef(oid) into definition from pg_constraint
  where conrelid = 'ingest.jobs'::regclass
    and conname = 'jobs_reviewed_coverage_schedule_allowlist_check';
  if definition is null or position(needle in definition) = 0 then
    raise exception 'Expected ordinal-27 reviewed coverage schedule constraint';
  end if;
  alter table ingest.jobs drop constraint jobs_reviewed_coverage_schedule_allowlist_check;
  execute 'alter table ingest.jobs add constraint jobs_reviewed_coverage_schedule_allowlist_check '
    || replace(definition, needle, needle || ', ''nanjakorya-paradigm-jp-100-v1''::text');
end;
$migration$;

do $migration$
declare
  reviewed record;
  evidence_hash text;
begin
  select contracts.*, policies.id as policy_id into strict reviewed
  from ingest.reviewed_public_study_contracts() as contracts
  join ingest.source_policies as policies
    on policies.source_key = contracts.policy_key and policies.config = contracts.config
    and policies.version = contracts.policy_version and policies.enabled and not policies.is_demo
  where contracts.ordinal = 28 and contracts.study_key = 'nanjakorya-paradigm-jp-100-v1';
  evidence_hash := encode(extensions.digest(convert_to(reviewed.evidence_excerpt, 'UTF8'), 'sha256'), 'hex');
  if evidence_hash <> 'ee845effa99200b85ff4380f16380f80aeec68a5398fc7d68a4b552c2cb16203'
    or reviewed.config ?| array['qualifying_hit_pack_count', 'qualifying_metric', 'metric_version'] then
    raise exception 'Paradigm Trigger complete-report evidence contract drifted';
  end if;
  insert into ingest.public_study_coverage_observations (
    study_key, source_policy_id, country_code, country_name, source_observed_at,
    pack_count, set_external_id, product_scope, collector_version, parser_version,
    source_policy_version, evidence_sha256, first_verified_at, last_verified_at, is_demo
  ) values (
    reviewed.study_key, reviewed.policy_id, 'JP', 'Japan',
    (reviewed.config ->> 'observed_at')::timestamptz, 100, 's12', 'all',
    reviewed.policy_version, reviewed.config ->> 'parser_version',
    reviewed.policy_version, evidence_hash, statement_timestamp(), statement_timestamp(), false
  );
end;
$migration$;
commit;
